### ISSUE TITLE
Blacklist haystacks from Art of Growing

### ISSUE THREAD

**Issue by LarekFlynn** [Hellaeh/vs-mods#2]
I also submitted this to Fedarmens (https://mods.vintagestory.at/list/mod?userid=458)

When using Quick Stack along with Art of Growing(https://mods.vintagestory.at/artofgrowing), haystacks can get over 128 items. Right-click to remove items then creates this crash. 

Just breaking the haystack, safely drops its contents.

Critical error occurred in the following mod: artofgrowing@0.0.4
<details><summary>Loaded Mods</summary>
<p>
detonateredux@1.1.1, degrees1499@1.0.0, acorns@0.5.3, aculinaryartillery@1.2.1, advancedsmithing@1.3.0, africanmonitorlizards@1.0.7, Armorlite@1.1.0, arrowheadsrecovery_fork@1.0.0, asianmonitorlizards@1.0.1, atwatersedge@1.5.0, axleinblocks@1.19.8-rc.1, balancedthirst@0.0.44, bamboom@0.2.1, bandedgeckos@1.2.0, beardeddragons@1.0.0, bearhidepatches@1.1.1, betterbricks@1.1.1, bettercompost@1.0.2, easyjam@1.0.0, bf@0.0.2, BetterGrass@0.0.3, bettershears@1.0.0, irregularguyboltheadsrecovery@1.0.1, explosivevanvar@0.0.5, brigandinerebalance@1.0.0, buckets_stack_to_5@1.0.1, buzzwords@1.7.0, cairns11bigcairn@1.1.0, cellardoor@1.4.0, charcoalpitrebalance@1.0.1, chargedjump@1.0.3, chiblocksel@1.0.5, chiseltools@1.12.10, claycasting@1.2.0, clayfromdirt@1.0.3, clickuptorches@1.1.1, Clothez@1.0.0, coloredsashes@1.0.0, compass2@3.0.0, landformoverhaul@0.0.2, coreblast@0.1.2, crackedrockweak@1.0.0, craftingjonas@1.0.6, creaturescan@1.0.10, cumanhelmet@0.7.5, cutthefat@1.0.1, decor@1.1.6, directstrongtannin@1.0.0, distillationinfo@1.0.0, dont-place-sticks@1.0.1, dryable_ground_storage@1.0.0, DrystoneParity@1.0.0, dye_recipes_fix@1.1.0, eldritchcuteclothing@1.0.2, ensatinas@1.0.0, entitiesinteract@1.0.11, evaporite@1.0.0, explosive@0.0.5, extendedcrafts@1.1.4, morecropsfix@1.0.6, farmlanddropswithnutrients@1.1.1, fernslikegrass@1.1.0, fibersfromtwine@1.0.1, fieldsofgold@2.1.6, firewoodfrombamboo@1.0.0, flourbags@1.0.5, caninae@1.0.16, capreolinae@1.1.5, casuariidae@1.0.8, dinornithidae@0.9.0, machairodontinae@1.0.9, manidae@1.0.2, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, free_stone_drops_when_broken@1.0.1, geoaddons@1.3.6, giantgouramis@1.0.2, gildedsteel@1.0.5, hammercrushed@1.0.0, HangingOilLamps@1.0.1, healthiertrees@1.0.0, hideandfabric-net7u@1.3.1, icyexc@1.0.0, ifozclothes@1.1.1, immersivecorpsedrop@1.0.2, immersivejavelins@1.0.1, immersiveorecrush@1.2.1, indappledgroves@0.8.5, ingotheating@1.0.2, jackscomposting@1.2.1, japanesemod@1.3.6, juicyores@1.0.0, knappingmastery@1.0.1, knobtailedgeckos@1.2.1, lanternliner@0.1.0, lanternpost@1.0.8, leopardgeckos@1.2.2, lithocraft@0.3.3, longtermfood@0.0.5, meatup@0.1.1, meltingpp@1.0.3, metaldetector@1.0.1, millwright@1.1.7, molds@0.1.1, morecrystals@1.2.0, moredrygrass@0.2.0, morenails@1.1.0, moreparchment@1.0.0, MoreTorchHolders@1.0.0, mycodiversity@1.0.2, nacatfish@1.0.1, nadarters@2.0.0, nasalamanders@1.0.0, naturalclay@1.1.1, newworldgianttortoises@1.1.1, pondfrogsiii@1.2.3, newzealandfrogs@1.1.1, unochre@1.2.0, oils@1.2.2, pondfrogsi@1.2.3, orepulverizer@1.1.1, pacificnewts@1.3.1, PartialLandslides@1.0.0, peacockbasses@1.1.2, pipeleaf@1.8.0, cbetterfertilizer@1.1.0, primitivesurvival@3.6.5, pulverizegrindables@1.0.0, unpfix@1.0.0, quicklimepk@1.0.0, rainfrogs@1.2.1, rawhideclothrot@0.0.1, bpip@0.0.9, realshingles@1.0.2, redblackbronze@1.0.0, ripened_wild_crops@1.0.0, rlmoonsun@0.1.2, rope-bridges@1.1.0, ropebridgescompatibility@1.1.0, russianmod@1.1.1, saltandsands@1.0.2, salty@1.0.1, scatastrophe@1.1.2, she1fish@1.2.1, shepherdmod@1.0.2, simplerails@1.0.0, speararrowheadbits@1.1.0, SpeedBoostCraftables@1.0.2, sticksfromfirelogs@1.3.0, superfuelresumed@2.1.3, swordz@1.1.8, swordzcompat@1.0.1, litbrig@0.5.0, thatchexpanded@1.1.1, truesunfishes@1.1.2, untamedwildsursidae@1.0.8, usefuldrifterloot@1.1.0, viesblocks@2.4.12, game@1.19.8, wallpaperblocks@2.0.0, wallpaper@1.0.0, warriordrink@1.0.2, wild_cabbage_pumpkin@1.0.0, zoombuttonreborn@2.0.0, abcsreborn@0.2.2, alchemycompat@1.0.0, alchemy@1.6.34, all_crates_matter@1.0.0, ancienttools@1.5.18, animationmanagerlib@0.8.8, apegrapes@1.1.1, apelanterns@1.0.0, apewindows@1.1.0, wrenchroof@1.1.0, artofgrowing@0.0.4, augplantlib@0.0.3, flags@0.33.1, barreldough@2.0.0, beartrap@1.1.1, bedspawnv2@1.2.0, beehivekiln@1.6.1, beltcraft@1.0.0, berrybushfixes@1.1.2, betterbloomeriesreborn@1.0.5, bettercaveart@1.1.1, betterentityinteraction@1.0.0, betterfirepit@1.1.4, betterfpcamera@1.2.0, betterhewnfencegates@1.0.0, betterstonepath@1.0.3, biggercellars@1.0.0, blacksmithenhancements@1.0.5, bodyheatbarfix@1.0.1, butchering@1.6.8, butterflycases@1.0.1, cancrops@0.2.6, canjewelry@0.3.6, carryon@1.7.4, charcoalpitdoor@1.0.0, chickenfeed@1.1.3, clearerquartzfix@1.0.0, clipfix@1.0.7, commonlib@2.5.0-rc.2, composter@1.1.0, craftembers@1.0.0, Crateful@1.2.8, creaturekilledby@1.0.0, crosscomme@1.0.10, cuniculture_fixed@1.0.4, danacancook@0.2.4, danatweaks@3.2.4, deconstructchutes@1.0.1, displaycasewall@1.0.3, doubleslabs@0.1.2, electricity@0.0.11, evenjugincrements@1.0.0, expandedfoods@1.7.2, extrachutes@1.0.0, extrainfo@1.8.1, fancyclouds2d@1.1.0, fancyplanters@1.2.0, helfavorite@0.3.5, fenceclimbable@1.0.0, fieldsofsalt@1.2.1, foodshelves@1.3.1, fromgoldencombs@1.6.3, fruitpressmashfix@1.0.1, furniturelibrary@1.0.11, gggenchem@0.2.0, golb@1.0.0, gourmand@1.2.4, hangingbaskets@1.1.0, hardcoreutilities@1.2.0, heatretention@1.0.2, herbarium@1.3.0, highfert@1.0.1, hit@2.1.2, hydrateordiedrate@1.4.8, immersivetpscamera@1.0.5, improvedhandbookrecipes@1.0.0, itemframe@1.0.0, jayuscookbook@1.0.2, kegrevivedagain@1.1.0, kevinsfurniture@1.2.0, kscartographytable@1.0.1, ksrealisticfarming@1.0.2, lc@1.0.0, labeledtrunk@1.0.5, lavoisier@1.3.0, lichenredux@1.8.3, liquidcontainers@1.2.0, lubricant@1.2.2, maltiezbows@1.0.4, manualdough@1.0.4, manualscraping@1.0.2, medievalexpansion@3.13.1, metaltongs@1.1.3, mio@0.9.5, meteoricexpansion@1.2.5, middleclicktostow@1.0.0, mif@1.0.1, minimalcompass@1.0.2, moreanimals@1.3.5, morepiles@1.5.0, moreplaster@1.0.2, mouse4and5@2.0.0, mcrate@1.2.1, mushroomz@1.0.2, naturalnight@2.1.0, nodrunkenshaking@1.0.1, spearexpantion@0.2.0, oneroof@1.1.1, particlesplus@1.1.0, passthruchutes@1.0.1, simplewinddirectionpelagus@1.0.0, petai@2.2.6, pickbars@1.0.0, pigfeed@1.0.4, pileful@1.1.5, pomshadercache@1.1.1, postsandbeams@1.3.2, claywheel@1.1.1, powdermanufacturing@0.0.2, precisepickedup@1.0.2, RareDenseOres@0.2.6, redbricktweak@1.0.0, resurgencepack@1.6.0, rivers@3.1.0, rockstratavariety@0.0.1, sailboat@1.3.1, scarecrow@1.5.1, seashellore@1.0.0, shovelimpervioustosnow@1.0.0, simplecloth@1.0.2, simplestep@1.1.7, simpletailoring@1.0.1, smithingplus@1.1.2, somethinginthewater@1.2.4, starvation@1.0.5, steamandpower@1.6.4, steelanvil@1.0.0, stillnecessaries@1.1.2, stonebakeoven@1.1.3, survivalexpanded@0.2.3, talderzeit@0.2.2, tarmor@0.2.2, thecritterpack@0.9.1, thirdperson_crosshair@1.0.0, toolworks@1.8.1, trailmod@1.0.8, tstools@2.1.2, usefulstuff17@1.3.2, vanillacratecompatibility@1.0.0, vanvar@5.0.4, versionchecker@1.0.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, warmarmor@1.1.0, wgmt@1.0.2, whatbagwasthatagain@1.0.1, wildfarmingrevival@1.2.5, workbenchexpansion@1.8.0, xlib@0.8.6, yummyfoods@1.0.4, alchemistry@1.0.2, beehivekilnwithclay@1.0.0, betterbamboo@1.0.2, bookbinders@1.1.1, bugnetcompatibility@1.0.1, bullseye-continued@2.5.8, butcheringbloodsausages@1.0.1, cancropsprimitivesurvivalcompat@1.0.3, cokemakesense@1.0.1, configlib@1.3.13, constructionsupport@0.1.2, detailedanimals@0.1.6, dowsedinsalt@1.0.0, electricityaddon@0.0.7, electricityextensions@0.0.7, em@2.7.0, extraoverlays@1.4.0, feverstonehorses@1.6.1, flammablefirestarter@1.0.1, fruitpresstweaked@1.0.1, fsmlib@0.4.5, glassmaking@1.4.0, immersiveinventoryspoilage@1.0.0, justchairs@0.0.1, laverace@1.0.3, morecandles@1.2.2, morefloors@2.1.1, newworldcrops@0.0.8, onestick@1.0.1, pickupartist@0.2.0, pickupfast@1.0.2, plankable-nmnd@0.1.2, porridgewithmilk@1.0.0, helquickstack@0.4.2, RedDyeFromBerries@1.1.1, sandwich@1.2.2, shearlib@1.0.1, slanted_display_cases@1.3.2, expandedfoodscheese@1.0.0, stainedbeams@1.0.0, cookie12000stickbeam@1.1.0, stonepiles@1.1.2, stonequarry@3.3.1, thriftysmithing@1.2.0, toolworksadditions@1.3.2, treetapping@1.0.0, Uncrustables@1.0.0, vanity@2.2.0, vsrecipes@1.2.3, wattleworldrevised@1.1.0, wildcraftfruit@1.2.2, wildcraftherb@0.0.1, wildcrafttree@1.2.0, xinvtweaks@1.6.6, xskills@0.8.8, bricklayers@2.5.6, cancropsxskillscompat@1.0.7, chickenfeedwildcraftfruitcompat@1.0.0, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4, maltiezspears@0.1.6, maltiezswords@0.0.1, statushudcont@2.1.2, tailorsdelight@1.7.1, ashes@1.0.0, wildberrydye@0.0.1, wool@1.2.2, xskillscatchablepatch@1.1.1, banners@0.1.1, bricklayerglassmakingcompat@1.0.2, dressmakers@1.4.0, upholstery@1.0.1
</p>
</details> 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArtOfGrowing.Blocks.AOGBlockGroundStorage.GetPlacedBlockInteractionHelp(IWorldAccessor world, BlockSelection selection, IPlayer forPlayer) in E:\Nik\vsmod\ArtOf\ArtOfGrowing\ArtOfGrowing\Blocks\AOGBlockGroundStorage.cs:line 374
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.ComposeBlockWorldInteractionHelp() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 281
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 499
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Hellaeh** [comment]
Thanks for the report! I don't really want to start blacklisting inventories of 3rd party mods. 
An ideal solution would be either - add ability to blacklist with config, or better blacklist with GUI interaction. I'll see what i can do when i have time. Won't be anytime soon tho.

**Comment by Hellaeh** [comment]
Fixed 5c1d51b
